### ISSUE TITLE
./build_supports.sh : Installation not successful

### ISSUE THREAD

**Issue by rrustagi20** [ivalab/gf_orb_slam2#5]
./build_dep_ubuntu20.04.sh was successfully executed

File not found 
![image](https://github.com/user-attachments/assets/be570957-8266-416d-b1ef-ef58ea7b096e)

issue building armadillo-11.2.4.tar.xz
![image](https://github.com/user-attachments/assets/00e14dca-9dd9-4aee-b50b-09f432b41b04)

![image](https://github.com/user-attachments/assets/3c51b636-9b9a-4aef-baa9-71a71cb38580)

and eventually
![image](https://github.com/user-attachments/assets/9d98d778-e90c-49c4-949e-81c838518178)

Any idea what is the reason? please note that `./build_dep_ubuntu20.04.sh` file was successfully executed

**Comment by shiyuF** [comment]
@rrustagi20 Since armadillo and eigen3 are compiled from "build_dep_ubuntu20.04.sh". You need to make sure those libraries are successfully compiled in the desired directory, which is defined by GF_ORB_SLAM2_ROOT. When compiling these third party packages, this macro directory will be used again to link to the correct locations. If the file does exist in the correct place, it won't have any problem. If it cannot be resolved, you can do a fresh compilation from executing "build_dep_ubuntu20.04.sh".

**Comment by rrustagi20** [comment]
resetting the GF_ORB_SLAM2_ROOT resolved it. Thanks!
